server:
  port: 7777
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/finance?characterEncoding=utf8&useSSL=true
    data-username: root
    data-password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 20
        max-wait: -1
    timeout: 1000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated  #有这个才会回调
    publisher-returns: true
    listener:
      type: simple
      simple:
        #手动确认
        acknowledge-mode: manual
        prefetch: 1   #限制每次发送一条数据。
        concurrency: 3      #同一个队列启动几个消费者
        max-concurrency: 3    #启动消费者最大数量
          #重试策略相关配置
        retry:
          enabled: true    #是否支持重试
          max-attempts: 5
          stateless: false
            #时间策略乘数因子
          multiplier: 1.0
          initial-interval: 1000ms
          max-interval: 10000ms
        default-requeue-rejected: true


